# Generated by Django 2.1 on 2020-02-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='jeep.jpg', upload_to='profile_pics'),
        ),
    ]
