# Generated by Django 2.1 on 2020-02-10 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 2, 10, 9, 38, 6, 831058, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
    ]
