# Generated by Django 2.1 on 2020-02-10 12:41

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20200210_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
